
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

input_number:
  car_tank_capacity_gal:
    name: Car Tank Capacity
    icon: mdi:gas-station
    min: 1
    max: 30
    step: 0.1
    initial: 11.9
    unit_of_measurement: gal
  car_avg_mpg:
    name: Car Average MPG
    icon: mdi:speedometer
    min: 10
    max: 100
    step: 0.5
    initial: 54.5
    unit_of_measurement: mpg

lovelace:
  dashboards:
    tarrayna-car:
      mode: yaml
      title: Tarrayna's Car
      icon: mdi:car
      show_in_sidebar: true
      filename: dashboards/tarrayna_car.yaml
